# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoOgc < Formula
  desc "Generate OGC API - Tiles metadata from exiting XYZ tilesets."
  homepage "https://github.com/planetlabs/go-ogc"
  version "0.8.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planetlabs/go-ogc/releases/download/v0.8.2/go-ogc_Darwin_x86_64.tar.gz"
      sha256 "14377ea5241ecb0c32a84328a8fdc548ba4fc09bcbd8f7a05a29bab78f33ffb2"

      def install
        bin.install "xyz2ogc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planetlabs/go-ogc/releases/download/v0.8.2/go-ogc_Darwin_arm64.tar.gz"
      sha256 "d041df2dcd94ab454d6dc592fafb1406cb293012d4c8b75bf55b80a492220ba7"

      def install
        bin.install "xyz2ogc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planetlabs/go-ogc/releases/download/v0.8.2/go-ogc_Linux_arm64.tar.gz"
      sha256 "303e1d259efc954e208b74dd49e51ae274bfd4670d78faf0c55c47ffb322c918"

      def install
        bin.install "xyz2ogc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planetlabs/go-ogc/releases/download/v0.8.2/go-ogc_Linux_x86_64.tar.gz"
      sha256 "02379fac330a485bed54356149c0d43dd641f822cd2b25ffdc65cdc7c0c9f21a"

      def install
        bin.install "xyz2ogc"
      end
    end
  end

  test do
    system "#{bin}/xyz2ogc version"
  end
end
