# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoOgc < Formula
  desc "Generate OGC API - Tiles metadata from exiting XYZ tilesets."
  homepage "https://github.com/planetlabs/go-ogc"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planetlabs/go-ogc/releases/download/v0.8.0/go-ogc_Darwin_x86_64.tar.gz"
      sha256 "6487e86fd1c37faa7dc53685103c51a442ebfd0072caf547f98d9a1205f379f8"

      def install
        bin.install "xyz2ogc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planetlabs/go-ogc/releases/download/v0.8.0/go-ogc_Darwin_arm64.tar.gz"
      sha256 "57d1177afc32a523b35ebea17f698f13077f055e113f5b3c5d60f987befe31ec"

      def install
        bin.install "xyz2ogc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/planetlabs/go-ogc/releases/download/v0.8.0/go-ogc_Linux_x86_64.tar.gz"
      sha256 "aee5eda623caa581db632b17a6a3a95ef038eba7114ce5fc57382bb77023ef83"

      def install
        bin.install "xyz2ogc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planetlabs/go-ogc/releases/download/v0.8.0/go-ogc_Linux_arm64.tar.gz"
      sha256 "0944b77f446740cc269f71623fd57556961ad50b074f5d260825ea1ddd117bc9"

      def install
        bin.install "xyz2ogc"
      end
    end
  end

  test do
    system "#{bin}/xyz2ogc version"
  end
end
