# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoStac < Formula
  desc "Utilities for working with Spatio-Temporal Asset Catalog (STAC) resources."
  homepage "https://github.com/planetlabs/go-stac"
  version "0.26.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/planetlabs/go-stac/releases/download/v0.26.0/go-stac-darwin-amd64.tar.gz"
      sha256 "67a140a1e0165ce2ad19f9b35604ccafec1f6ae7eae271a4fbe9428fd8ad2663"

      def install
        bin.install "stac"
      end
    end
    on_arm do
      url "https://github.com/planetlabs/go-stac/releases/download/v0.26.0/go-stac-darwin-arm64.tar.gz"
      sha256 "3e8f834a0ca7af0e5a6939ccb3aab21c5bc1cc146ec9667a7fb8f3a7e40e7bbd"

      def install
        bin.install "stac"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planetlabs/go-stac/releases/download/v0.26.0/go-stac-linux-amd64.tar.gz"
        sha256 "2b31591798e92a34ddd51ece9d4079ccbea3c000f1555eee708b78dcc8cffab9"

        def install
          bin.install "stac"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planetlabs/go-stac/releases/download/v0.26.0/go-stac-linux-arm64.tar.gz"
        sha256 "094db90dfd02c150da5eac0a83e32b0e38347801792de77104b9a05869c895ea"

        def install
          bin.install "stac"
        end
      end
    end
  end

  test do
    system "#{bin}/stac version"
  end
end
