# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoStac < Formula
  desc "Utilities for working with Spatio-Temporal Asset Catalog (STAC) resources."
  homepage "https://github.com/planetlabs/go-stac"
  version "0.25.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/planetlabs/go-stac/releases/download/v0.25.1/go-stac-darwin-arm64.tar.gz"
      sha256 "c1a408eda3810767f230100a51c1621aaf9c6bb1943646e50182b91b2e8a7217"

      def install
        bin.install "stac"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planetlabs/go-stac/releases/download/v0.25.1/go-stac-darwin-amd64.tar.gz"
      sha256 "07ccf06de955cfdc5fa2b05ced009449a7a2b374c373ba4fe871f19251a3eac1"

      def install
        bin.install "stac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/planetlabs/go-stac/releases/download/v0.25.1/go-stac-linux-amd64.tar.gz"
      sha256 "0041c7baad958f0ac5da3f85c0f03f9aa15c3a6cebbfa2e0364e003f225326be"

      def install
        bin.install "stac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planetlabs/go-stac/releases/download/v0.25.1/go-stac-linux-arm64.tar.gz"
      sha256 "16c060de7a02f54642e81be1edd9f31d5419271bad82d8d1580987a3550ad4ad"

      def install
        bin.install "stac"
      end
    end
  end

  test do
    system "#{bin}/stac version"
  end
end
