# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpq < Formula
  desc "Utility for working with GeoParquet."
  homepage "https://github.com/planetlabs/gpq"
  version "0.23.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/planetlabs/gpq/releases/download/v0.23.0/gpq-darwin-amd64.tar.gz"
      sha256 "558845a97f60ed8757f5bf6a9f7a00495ec15683e05824eb3e9ee8ad63b35f2d"

      def install
        bin.install "gpq"
      end
    end
    on_arm do
      url "https://github.com/planetlabs/gpq/releases/download/v0.23.0/gpq-darwin-arm64.tar.gz"
      sha256 "ee9cba953383acbb9ace4f66156f90e8848d4fb51a6173731011e2c21d50a5f4"

      def install
        bin.install "gpq"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planetlabs/gpq/releases/download/v0.23.0/gpq-linux-amd64.tar.gz"
        sha256 "14fb9e99ea96609d39381e16a08b69bdad08a10bcc685d50fc6e9f5ad64d2d85"

        def install
          bin.install "gpq"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/planetlabs/gpq/releases/download/v0.23.0/gpq-linux-arm64.tar.gz"
        sha256 "77995b68588a7c861d9b358b74d901ccd4bbf2ee9fbcc9b6ac1d2c9ef41c0f0e"

        def install
          bin.install "gpq"
        end
      end
    end
  end

  test do
    system "#{bin}/gpq version"
  end
end
