# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpq < Formula
  desc "Utility for working with GeoParquet."
  homepage "https://github.com/planetlabs/gpq"
  version "0.16.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planetlabs/gpq/releases/download/v0.16.0/gpq-darwin-amd64.tar.gz"
      sha256 "73be8e826ba56e6167df3908ce3abfdd247540ab0569fe5b09794622cc03c1de"

      def install
        bin.install "gpq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planetlabs/gpq/releases/download/v0.16.0/gpq-darwin-arm64.tar.gz"
      sha256 "5f5412c96baaa56e20a5c832e0e69f12d912cf00984d5eaf6df6826d74658844"

      def install
        bin.install "gpq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planetlabs/gpq/releases/download/v0.16.0/gpq-linux-arm64.tar.gz"
      sha256 "87a02bc8a617b1e2447114469a4291f6f9fd7103f7a0e9fe7aa840b34d18e157"

      def install
        bin.install "gpq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planetlabs/gpq/releases/download/v0.16.0/gpq-linux-amd64.tar.gz"
      sha256 "c0a0d6474f315674a88ae2ef4cb4810daa4bef4cb46986e0fb170627026ae118"

      def install
        bin.install "gpq"
      end
    end
  end

  test do
    system "#{bin}/xyz2ogc version"
  end
end
