# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpq < Formula
  desc "Utility for working with GeoParquet."
  homepage "https://github.com/planetlabs/gpq"
  version "0.11.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/planetlabs/gpq/releases/download/v0.11.0/gpq-darwin-arm64.tar.gz"
      sha256 "320deeb76dc11ccdfcf76633c19012b56c460bb336ac97d77515fe9278deefbb"

      def install
        bin.install "gpq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planetlabs/gpq/releases/download/v0.11.0/gpq-darwin-amd64.tar.gz"
      sha256 "b04b9870e18f7ff25d5799240a979614978b9b0d1c83e9ccc0eef3c4aac2c972"

      def install
        bin.install "gpq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planetlabs/gpq/releases/download/v0.11.0/gpq-linux-arm64.tar.gz"
      sha256 "2fbac07737e4db378ce0d1bcd252babe9cb5a04e7f5d609762fa88338fe877c9"

      def install
        bin.install "gpq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planetlabs/gpq/releases/download/v0.11.0/gpq-linux-amd64.tar.gz"
      sha256 "e8ea6f96e440da33a748e688efc6a9cb8384a1e93b42fc8b297a3393a7abb2c6"

      def install
        bin.install "gpq"
      end
    end
  end

  test do
    system "#{bin}/xyz2ogc version"
  end
end
