# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoStac < Formula
  desc "Utilities for working with Spatio-Temporal Asset Catalog (STAC) resources."
  homepage "https://github.com/planetlabs/go-stac"
  version "0.18.0-beta.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planetlabs/go-stac/releases/download/v0.18.0-beta.8/go-stac_Darwin_x86_64.tar.gz"
      sha256 "0e998bb3b75b848c3f6c0ac95615fb65a70a095faf3e1e874ea17fc8f25b71e3"

      def install
        bin.install "stac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planetlabs/go-stac/releases/download/v0.18.0-beta.8/go-stac_Darwin_arm64.tar.gz"
      sha256 "358ac53a3a6c6cf8e6e934993c43ee56cf2405582477bb7d5496406bbb951343"

      def install
        bin.install "stac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planetlabs/go-stac/releases/download/v0.18.0-beta.8/go-stac_Linux_arm64.tar.gz"
      sha256 "5c7018c3a1156d6563803ef4c11af36774c2d265e9ccd1d790d10316fab8118f"

      def install
        bin.install "stac"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planetlabs/go-stac/releases/download/v0.18.0-beta.8/go-stac_Linux_x86_64.tar.gz"
      sha256 "c88f7ed83198f867d015f9d3b8969376c2d0749f068983792f1eb5bdc5b1aae3"

      def install
        bin.install "stac"
      end
    end
  end

  test do
    system "#{bin}/stac version"
  end
end
